# -*- coding: utf-8 -*-
"""Assignment - 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18NMlnUKnFc9nqXGuysFH2XIlHwOmzXgF
"""

import pandas as pd
df = pd.read_csv('/content/data.csv')

df

df.describe()

df.isnull().sum()

calories_mean = df['Calories'].mean()
df['Calories'].fillna(calories_mean, inplace=True)

df.isnull().sum()

df[['Calories', 'Pulse']].agg(['min', 'max', 'count', 'mean'])

df[(df['Calories'] >= 500) & (df['Calories'] <= 1000)]

df[(df['Calories'] > 500) & (df['Pulse'] < 100)]

df.drop(columns=['Maxpulse'])

df['Calories'] = df['Calories'].astype(int)

import matplotlib.pyplot as plt
plt.scatter(df['Duration'], df['Calories'], color='blue', alpha=0.5)
plt.title('Scatter plot between Duration and Calories')
plt.xlabel('Duration')
plt.ylabel('Calories')
plt.grid(True)
plt.show()

"""# 2) Linear Regression"""

df2=pd.read_csv("/content/Salary_Data (2).csv")
print(df2)

from sklearn.model_selection import train_test_split

X = df2[['YearsExperience']]
y = df2['Salary']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=42)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)

from sklearn.metrics import mean_squared_error

mse_train = mean_squared_error(y_train, y_pred_train)

mse_test = mean_squared_error(y_test, y_pred_test)

print("Mean Squared Error (Train):", mse_train)
print("Mean Squared Error (Test):", mse_test)

plt.figure(figsize=(10, 6))
plt.scatter(X_train, y_train, color='blue', label='Training Data')
plt.scatter(X_test, y_test, color='red', label='Test Data')
plt.plot(X_train, y_pred_train, color='green', linewidth=2, label='Regression Line')

plt.title('Linear Regression - Salary Prediction')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.legend()
plt.show()